### ISSUE TITLE
Excuse me, I want to consult the price of the DN latest server

### ISSUE THREAD

**Issue by 634287319** [alin1337/cloudflare-ddns#5]
Excuse me, I want to consult the price of the DN latest server tell me 634287319@qq.com

**Comment by AlleSoke1** [comment]
Hello [634287319](https://github.com/634287319), I have not been in touch or heard about DN for more than 7 years. Unfortunately, I no longer have any contact with the community, therefor I can't be of any help to you.

**Comment by 634287319** [comment]
oh okay！thank

**Comment by 634287319** [comment]
Do you know who has the latest Dragon Valley program？

**Comment by AlleSoke1** [comment]
No.
